### ISSUE TITLE
Issues changing the bootstrap

### ISSUE THREAD

**Issue by ageneauNOR** [appium/appium-android-bootstrap#28]
I have been compiling the bootstrap using mvn package -P 4.4. Then I put the jar in the jar directory for Appium.

When I run appium, it's behaviour doesn't change despite the modifications I have made.

Why doesn't it take it into consideration ?

**Comment by imurchie** [comment]
Because it is using the `appium-android-bootstrap` package from npm.

The solution is to "link" the two. In your `appium-android-bootstrap` directory, run `npm link`.

Then go into the Appium directory (whether you are running from source or from npm), then

```
cd node_modules/appium-android-driver
npm link appium-android-driver
```

The code that Appium runs for Bootstrap should now be used.

**Comment by ageneauNOR** [comment]
I'll give it a try, thank you very much.

**Comment by imurchie** [comment]
Sorry, I realize I mis-wrote the linked package. It should be 

```
cd node_modules/appium-android-driver
npm link appium-android-bootstrap
```

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7500](https://github.com/appium/appium/issues/7500) via [**ZenHub**](https://www.zenhub.com/)
